# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="my home directory and scripts 🐪🐚"
REPO_LICENSE=""
REPO_TOPICS="bash-prompt,bashrc-configs,perl,tmux"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/chicks-home.git"
REPO_WEB_URL="https://github.com/chicks-net/chicks-home"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="chicks-home"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "bash-prompt"
    "bashrc-configs"
    "perl"
    "tmux"
)
