# .repo.toml

[about]
description = "my home directory and scripts 🐪🐚"
topics = ["bash-prompt", "bashrc-configs", "perl", "tmux"]

[urls]
git_ssh = "git@github.com:chicks-net/chicks-home.git"
web_url = "https://github.com/chicks-net/chicks-home"

[flags]
claude = true
claude-review = true
copilot-review = true
standard-release = true
