#!/usr/bin/env bash
#
# This only works on public repos unless you have Github Pro.  Sorry about that.

USERNAME=$(gh api user --jq .login)

RULESET_FILE="$1"
REPO_NAME="$2"

# Check if ruleset config exists
if [[ ! -f "$RULESET_FILE" ]]; then
	echo "Error: $RULESET_FILE not found!"
	exit 1
else
	echo "Applying ruleset $RULESET_FILE to $USERNAME/REPO_NAME"
fi

# Use gh api to create the ruleset
gh api "repos/$USERNAME/$REPO_NAME/rulesets" \
	--method POST \
	--input "$RULESET_FILE" && echo "✅ Success: $REPO_NAME" || echo "❌ Failed: $REPO_NAME"
