---
name: MarkdownLint
on:
  push:
    branches:
      - main
  pull_request:

# global permissions
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: DavidAnson/markdownlint-cli2-action@1628d9b2c73e580b4cb9b6b34303457a72478c5e # v23
      with:
        globs: |
          **/*.md
          !.github/pull_request_template.md
