---
name: MarkdownLint
on:
  push:
    branches:
      - main
  pull_request:

# global permissions
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    # zizmor: ignore[unpinned-uses]
    - uses: actions/checkout@v6
      with:
        persist-credentials: false
    # zizmor: ignore[unpinned-uses]
    - uses: DavidAnson/markdownlint-cli2-action@v22
      with:
        globs: |
          **/*.md
