---
name: Validate Renovate config

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/renovate.json'
      - '.github/renovate/**'
      - '.github/workflows/renovate-validate.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/renovate.json'
      - '.github/renovate/**'
      - '.github/workflows/renovate-validate.yml'
  workflow_dispatch:

# global permissions
permissions: {}

jobs:
  renovate-validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Validate renovate.json
        uses: docker://ghcr.io/renovatebot/renovate@sha256:59556c9046c7901e610e9ddc61540db3b27964aae63ff652ad053b0fdd439933 # 43.233.1
        with:
          args: renovate-config-validator .github/renovate.json
